version: '3.7'
services:
  api:
    container_name: api
    image: api
    build:
        dockerfile: Dockerfile
        context: ./api
    environment:
      - HOST=mongo
    ports:
      - '4200:4200'
    volumes:
      - '/proc:/elements/proc/'
    depends_on:
      - mongo
  
  balanceador:
    container_name: balanceador
    image: balanceador
    build:
        dockerfile: Dockerfile
        context: ./balanceador
    environment:
      - HOST=mongo
    ports:
      - '80:5000'
    depends_on:
      - mongo


  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
